nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['*']
        expose_headers: ['*']
        max_age: 3600
        allow_credentials: false  # * origin ile true olamaz
    paths:
        '^/':  # Tüm path'ler için
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['*']
            max_age: 3600
